### PR TITLE
Add an id for the approval tabs' sections

### PR DESCRIPTION
**Pull request by lgalis**
Add an id for the approval tabs' sections - 'tab-title'

https://projects.engineering.redhat.com/browse/SSP-557

### CODE REVIEW

**Comment by Hyperkid123** [comment]
I see an page type attribute on section but no ids for tabs. Maybe different pr?

**Comment by lgalis** [comment]
@Hyperkid123 - the Tab elements have a 'name' attribute - should we have a common identifier property for all elements?

**Comment by Hyperkid123** [comment]
@lgalis i would just use classic `id` attribute if its possible. I know that some PF components do not assign them correctly though.

**Comment by lgalis** [comment]
@Hyperkid123 - agree - the Tab elements do have an id, the Section ones do not. The Insights components adds the page-type property. I can add an 'id' as well

**Comment by Hyperkid123** [comment]
@lgalis i will merge this one i went through the jira ticked and i can see what was the purpose of this. I would add the Ids globally to control elements (links, buttons etc.) in different pr.

**Pull request merged**
