### PR TITLE
Update the schema for the add/update workflow to use field_array

### PR DESCRIPTION
**Pull request by lgalis**
Update the schema for the add/update workflow to use a field array, and allow a dynamic number of stages to be added.

Add - select stages:
Screenshot from 2019-05-29 15-02-55

Summary
Screenshot from 2019-05-29 15-03-08

List with the added stages:
Screenshot from 2019-05-29 15-03-32

Edit Workflow:
Screenshot from 2019-05-29 15-03-51

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@lgalis do we have any mocks for the dynamic fields? Current PF4 implementation has just placeholders.

**Comment by lgalis** [comment]
@Hyperkid123  - the only mocks I have seen with dynamic fields are the ones for this modal: 
https://redhat.invisionapp.com/share/T2PQRHIS534#/screens/339848080

**Comment by Hyperkid123** [comment]
> @Hyperkid123 - the only mocks I have seen with dynamic fields are the ones for this modal:
> https://redhat.invisionapp.com/share/T2PQRHIS534#/screens/339848080

Ok i will get touch with some PF guys and update the forms accordingly

**Comment by gmcculloug** [comment]
@lgalis @Hyperkid123 Do we still need this PR or can it be closed?

**Comment by Hyperkid123** [comment]
@gmcculloug i think this can be closed it was already done in other PRs

**Pull request closed without merging**
